### ISSUE TITLE
「エイリアス」の綴り

### ISSUE THREAD

**Issue by RPGP1** [t-tutiya/tsukasa#1]
ailiasと綴られているようですが、aliasではないでしょうか？

**Comment by RPGP1** [comment]
プルリクしましたのでcloseします

**Comment by t-tutiya** [comment]
>ailiasと綴られているようですが、aliasではないでしょうか？
ぎゃ、ぎゃー！　ありがですー！＞＜

**Comment by t-tutiya** [comment]
マージしてから気づいたけど、rubyの予約語のaliasと被ってますね＾＾；
ひとまずスクリプトのコマンドは大文字のALIASにしましょう（次のコミットで対応します）。
このruby予約語系（if/whileなど）もどうしたものか考え中。

最低限このコードでの動作を確認して欲しいみたいなサンプルスクリプトを作るべきかな。めんどくさいー＞＜

**Comment by RPGP1** [comment]
あらら…本当ですね。
予約語の回避は難しいですね。Rubyの中でDSLを構築している限り予約語はそのまま使えませんからね。

Racc等でパーサを作れば回避できそうですが…うーむ。面倒。
そうでなければ(大文字にするのも含め)別の名前を与える他に無さそうです。
(この分野に詳しい訳では無いので、他の手段が有るのかも知れないです)

因みに以前、予約語も気にせず使うために、正規表現だけでコマンドシステムを作ってみたのですが、やはり処理が重すぎました(当たり前(笑


サンプルに関しては、仕様が一通り確定してからで良いような気がします。


これらの議題について、各々Issueを立てると良いのですかね？

**Comment by t-tutiya** [comment]
・最終的にはこのスクリプトの更に上位にリプレーサーを用意して、ユーザーには吉里吉里ライクなシナリオを書いてもらい、それを現在のスクリプトにリプレースする形にしたいと考えています（シナリオとスクリプトは独立しているので、各自が流儀に合ったシナリオリプレーサーを作るイメージ）。
・その意味では、スクリプトレベルでは予約語になる物は"tsukasa_alias"とかにしちゃっても良いかもですね。
・ただ、リプレーサーはまだ作る余裕が全然ないので、当分先になるので、ひとまずはALIASのように大文字化で対応しましょう。

>これらの議題について、各々Issueを立てると良いのですかね？

よろしくーです。助かります。実はgithub全然使ったことないので、流儀が全然わかっておらず、助かります。
毎回コミット／プッシュしてるけど、実験的にコード書き換える時はブランチ（だっけ？）切った方がいいのかなーとかそういうレベルでわかってない。

**Comment by RPGP1** [comment]
なるほど！分かりました。

Githubの使い方は私も分かってません(笑)
ブランチは…私のようなフォークした側は必須だと思いますが、この小規模なプロジェクトなので、マスターは大丈夫かもしれません。
あおたくさんとかは、昨年末にタイムトライアルでGithubの経験を積んでた気がしますが。

**Comment by aoitaku** [comment]
呼ばれた気がしてやってきました。

> 実験的にコード書き換える時はブランチ（だっけ？）切った方がいいのかなー

そうですね、できるかぎりそうしたほうがいいと思います。
本当は master ブランチには安定版を指すようにして、development のような名前で開発用のブランチを作ってそこで作業をするのが推奨されています。で、機能毎にブランチを作って、機能ができたら development にマージ、development に機能が揃って安定したら master にマージ、という感じです。

……といいつつぼくも SpriteUI のリポジトリ見ると分かるんですが master にガンガンコミットしてたりします。これはちょっと言い訳っぽいんですが個人開発のリポジトリについては最初の安定版が出るまでは master 上で開発を進めちゃっていいんじゃないかなーと思っています。
一度安定版が出るとバージョン間の互換性を維持しないといけないし、「master ブランチは常に動くものが存在する」という状態を保ったほうがいいのですが、安定版リリース以前は流動的に仕様を変えられるような体制のほうがやりやすいと思うので。

> これらの議題について、各々Issueを立てると良いのですかね？

issue も議題単位で作ったほうがよいと思います。
個人的にはできるだけ小さな単位でissueを作りたい派（そのほうがコミットと紐づけしやすい）なんですが、具体的になりすぎるので、もうちょっと大きな単位で作ってプルリクエストベースで扱う、としてもいいかもしれません。

**Comment by RPGP1** [comment]
おぉー！ありがとうございます。

(突然あおたくさんを呼んですいませんw。自己紹介します。
 Twitterで[ハイド](http://twitter.com/gamekazu)やってる者です)

**Comment by aoitaku** [comment]
はい、知ってますぞ（ﾆｯｺﾘ

**Comment by t-tutiya** [comment]
>あおたくくん

ありがー！＞＜
じゃあしばらくはmaster直接弄るわー。
そうだな、あおたくがリプレーサー実装してくれるまでそれでいこうかなー（メガネをきらっと光らせる）

>Twitterでハイドやってる者です

わかってるがなｗ

**Comment by RPGP1** [comment]
い、いや、一応ですよ(^o^)

**Comment by aoitaku** [comment]
> そうだな、あおたくがリプレーサー実装してくれるまでそれでいこうかなー（メガネをきらっと光らせる）

₍₍ ᕕ( ᐛ )ᕗ⁾⁾ （がんばりますの意
