### ISSUE TITLE
コマンドif, while, call_procedureにおけるevalの使用について

### ISSUE THREAD

**Issue by RPGP1** [t-tutiya/tsukasa#10]
単純にコマンド配列を送らない理由として、ローカル変数'options' (と'target') の参照をしたいから、というのが有るように思えますが、
これ以外に理由は有りますか？

具体的には、evalされる文字列の中で、これら以外の変数(インスタンス変数やクラス変数)にアクセスさせる状況などは想定していますか？
逆に「アクセスさせない方が良い」と思いますか？

**Comment by t-tutiya** [comment]
これなにげに良い質問ですが、

>ローカル変数'options' (と'target') の参照をしたいから

というわけでないです。
if/whileもコマンドとして各コントロールに送信され、例えば以下のようなコードが動く事を想定しています。

IF "false" do
  THEN do
    EVAL "pp 'true3'"
  end
  ELSE do
    EVAL "pp 'false4'"
  end
end

evalされるのは"false"の所で、ここを実行時にruby式を評価したいのです。なんでかというと「他に条件式を記述する方法がないから」という消極的な理由です。if/whileが実際にどのように使われるのかについてもまだよくわかってないので、将来的には上手い条件式の設定方法が見つかるかもしれませんが、ひとまずこのままにしておいてください。

call_procedureは、一連のコマンド群に対して、実行時に引数を設定出来る、関数としての使い方を想定しています（その為、実行時にevalされる）。ただ、これももっと上手い方法があるのではないかと考えています（直近の作業でprocedureが必要ない為、今は実行されないようにしています）。これもひとまずはこのままでよろーです。

**Comment by t-tutiya** [comment]
これも参照
http://d.hatena.ne.jp/t_tutiya/20150208

**Comment by t-tutiya** [comment]
以前のコードはこうなってた。

procedure :log,
  impl: <<"EOS"
    [[:create, {:create => :ImageControl,
      :file_path => options[:file_path], 
      :x_pos =>     0, 
      :y_pos =>     0, 
      :id =>       :test}]]
EOS

この記述は面倒なので使いたくないですね……。

aliasの方では、ひとまずaliasされたコマンド群送信してから、改めてブロックで指定されたコマンドを発行することで、（change_imageとかで）後からコントロールのプロパティを更新すれば、引数を設定しているのと同じことになるのではというアプローチを試しています。

**Comment by RPGP1** [comment]
色々と読んできました。
手続きオブジェクトを渡すのはどうでしょうか？

一言で言うと、
評価を保留して実行時に行うことも、
引数を渡すことも、
可能だと考えます。

**Comment by RPGP1** [comment]
[手続きオブジェクト](http://docs.ruby-lang.org/ja/2.1.0/doc/spec=2flambda_proc.html)というのは、ブロックをオブジェクトにしたものですから、
ハッシュに入れて管理しておいて後から実行できますし、
コマンド呼出のオプションに格納できます。
直接、引数を渡すことも可能です。

また、コンテキスト(変数などの環境)をいじることで、ブロック内で扱えるローカル変数に代入してから実行もできます。

**Comment by t-tutiya** [comment]
構わないけど、それってどうやって記述します？

**Comment by RPGP1** [comment]
最初の例を再現するならば、次のようになると思います。

```ruby
IF -> { false } do
  THEN do
    EVAL "pp 'true3'"
  end
  ELSE do
    EVAL "pp 'false4'"
  end
end
```

**Comment by RPGP1** [comment]
こういった事も出来るでしょう。

```ruby
count = 0 #前に代入した変数を
WHILE -> { i < 10 } do
  count += 1
  p i
end
```

**Comment by RPGP1** [comment]
取り敢えず実装してみますね。
問題が有れば却下して下さい^^

**Comment by t-tutiya** [comment]
んーむ、ありな気がする

**Comment by RPGP1** [comment]
あおたくさんのこのブログ記事 → http://blog.aotak.me/post/69272692495/show-off-parentheses
の「ブロック引数」の項を参考にしました

**Comment by RPGP1** [comment]
話しがそれるのですが、
ifを弄っていたら

```ruby
IF -> {true} do
  #真の場合
ELSE()
  #偽の場合
end
```
みたいに書けるようになったのですが、元の方が良いですか？

問題点は、elseに当たる部分だけだと思います。
予約語なのでelseはそのまま使えませんし、
引数もブロックも渡さなくなったので`ELSE`は使えなくなってしまって…(`ELSE()`と括弧を付ければ大丈夫ですが)。

**Comment by RPGP1** [comment]
[no_eval](https://github.com/RPGP1/tsukasa/tree/no_eval)というブランチを作ってコミットしてみました。
テストシナリオを作ったので、確認してください。

**Comment by t-tutiya** [comment]
$B!D!D$s!)(B
$B<+J,$G=q$$$?$O$:$J$N$K!"$J$s$G$3$l$GF0:n$9$k$N$+$,J,$+$i$J$$(Bw
ELSE$B$O%3%^%s%I$G$O$J$/!"C1$K%-!<L>$rJQ$($k%a%=%C%I$C$F$3$H$J$N$G$7$g$&$+!)(B $B%-!<L>$rJQ$($?;~E@$G$=$l0J9_$N%3%^%s%I$,3JG<$5$l$k%O%C%7%e$,@Z$jBX$o$k$+$i!"$=$l$GF0$/$N$+$J!)(B
$B$@$H$9$k$H!"$b$7$+$7$F(Belsif$B$b<BAu$G$-$?$j$7$A$c$$$^$9$+$M!JJ#?t;XDj$G$-$?$i$J$*NI$$(B)
$B85!9(Belse$B$O%3%^%s%I$H$O8@$$$,$?$$$N$G!"$3$N%"%W%m!<%A$ONI$$%"%$%G%"$@$H;W$$$^$9!#$?$@!"$9$08!>Z$G$-$J$$$N$G!">/$77P$C$F$+$i%W%k%j$7$F$b$i$C$F$bNI$$$G$7$g$&$+!#(B
$B$A$g$C$H:#D>6a$G:n$i$J$-$c$J$i$J$$%G%b$,2B6-$KF~$C$F$F$7$P$i$/%A%'%C%/$G$-$J$$$b$G$9!#$4$a$s!*!d!c(B

**Comment by RPGP1** [comment]
文字化けしてますよー
