### ISSUE TITLE
設計意図の共有を目指す

### ISSUE THREAD

**Issue by RPGP1** [t-tutiya/tsukasa#12]
このIssueの目的
---

「ツイッターで話題に上ったので、Issueを立てて会話し、記録に残していきたいな」

**Comment by RPGP1** [comment]
## systemの構成

systemフォルダの中にあるファイルは以下のような分類で良いかと思います。

### コードツリートップ

* rag.rb

main.rbが呼び出すファイル。このファイルが他のファイルを呼び出す。

### 根幹

* control_container.rb

「司」が画面上で扱う全てのオブジェクトの基礎Controlクラスを定義している。

* script_compiler.rb

「司」はコマンドでコントロールを制御する。シナリオからコマンド配列を生成する部分で、必然的にコマンドの定義の一翼を担う。

### 補助モジュール

* module_movable.rb
* module_drawable.rb

順に移動、描画の機能を提供するモジュール

### サブクラス群

残りはControlのサブクラス(まだ読んでいないので、読み次第追記する)

**Comment by RPGP1** [comment]
## 「根幹」の作るもの

根幹の2ファイルのみを読んで得た感覚です。

### コントロールツリー

createコマンドで作成された子コントロールを配列に格納し、updateやrender, コマンドを伝搬する。

### コマンドの時間差評価

シナリオはコンパイル時にコマンドの配列に変換され、実行時まで保持される。実行時にはコマンドを順に取り出し評価する。条件式やプロシージャは変換も無くそのまま保持され、必要になった時に評価される。

**Comment by t-tutiya** [comment]
合ってるー。
・ragは旧名称なので、rag.rbはいずれ名前を変えます
・script_compilerではコマンドの引数仕様（単一の無名オプション／ハッシュオプション群／ブロックのどれを受け取るのか）に制約を与えたいと思っているのですが、面倒であんまり厳密にやってません。
・スクリプトは、例えば「テキストレイヤのページ送りを示すアイコン」のアニメーションパターンを単一のスクリプトファイルとして記述し、create時にパスを指定しておくと自動的にそのファイルを読み込む、とういことがしたいと思っています（まだできてない）

**Comment by RPGP1** [comment]
ありがとうございます^^

**Comment by t-tutiya** [comment]
整理の為に一旦closeしますー。
