### ISSUE TITLE
IF文の文法について

### ISSUE THREAD

**Issue by RPGP1** [t-tutiya/tsukasa#13]
現在のコードではTHENもELSEも複数存在できるんですが、これはアウトですよね？

**Comment by t-tutiya** [comment]
あーそうかアウトだ。
ただ、そもそもoptions[:then]/options[:else]で受け取れて良いのかというのがあって（ＮＧな気がしている）、その辺はまだ設計があいまいです。defineから初めてもらえるとチェックしやすいかも（次はラムダ条件式）

**Comment by RPGP1** [comment]
では…
今バグ取りをしてるのですが、複数THEN/ELSEは一旦放置ですね？

**Comment by t-tutiya** [comment]
ひとまず放置でお願いしますー。
作ったはいいけどまだif条件文を必要とする所までデモが進んでないのよね……

**Comment by t-tutiya** [comment]
バグも１個のバグに付き１個のプルリでよろしくーです。焦らず細かく行こう。

**Comment by RPGP1** [comment]
\(^ okay ^)/

**Comment by RPGP1** [comment]
ELSIF文の実装を目指すので、reopenします

**Comment by RPGP1** [comment]
現状の問題(?)がもう一つ見つかりました。THENやELSEがIFの外でも置けます。(勿論実行はされません。)

**Comment by t-tutiya** [comment]
>THENやELSEがIFの外でも置けます。
やっぱりthen/elseの扱いがおかしい気がする。
thenもelseもblockのシンタックスシュガーにして、ブロックになんらかのパラメーターを付与できるようにして、そこで:then/1/2/3/.../:elseとか属性与えるかね（1/2/3はelfifの順番指定）

**Comment by RPGP1** [comment]
因みにELSIFできました #26

**Comment by RPGP1** [comment]
THENでもELSEでも、@key_nameを変えますよね？
その時、返る前の値をチェックすることでこの問題は解消されます。

**Comment by RPGP1** [comment]
あくまで個人の意見ですが、
一度没にした「THENを廃止する」案は、こうした問題やELSIFが加わった上での記述効率等を考えて、再考の余地があると思います。
例えば、elseは_ELSE_とすれば括弧は要らなくなります。

それに他の予約語同様、リプレーサーさえあれば名前の衝突は無視できます。

**Comment by t-tutiya** [comment]
さんきゅーですー。
THENを廃止するかどうかについては、リプレーサーを設計する段階で、script_compilerがどのようなコードを吐くべきかについて再検討したいと思います。ひとまずこれで行きましょう。

**Comment by RPGP1** [comment]
分かりました。
@key_nameのチェックはどうしましょう？

**Comment by t-tutiya** [comment]
可能ならお願いします－＞チェック

**Comment by RPGP1** [comment]
やってみました #27

**Comment by RPGP1** [comment]
これで、残りの文法上の問題は
「IFブロック内の、どの節にも属していない部分にコマンドが打てる」
ということだけになりました

**Comment by t-tutiya** [comment]
それはリプレーサー側で制限しようかな……（こうやってリプレーサーの要求仕様がどんどん増えていく）

**Comment by t-tutiya** [comment]
整理の為に一旦closeしますー。
