### ISSUE TITLE
functionにブロックを付与したい意図について

### ISSUE THREAD

**Issue by t-tutiya** [t-tutiya/tsukasa#29]
プッシュしたコードだと意図が実装しきれてないのだけど、ひとまず希望表明だけしておきます。

　やりたいのは「functionが実行された際に、（これ自体微妙だけど）そのfunction内にスコープを限定し、そのスコープの中にある任意コントロールにコマンドを送信したい」ということです。

　なんでかというと、同一のfunctionを複数回実行した場合、コントロールツリー上に同一ＩＤのコントロールが複数存在することになる（これ自体は問題無い）ので、その際に、今実行したfunctionを対象にコマンドを送信したいのです。

　正しく実装する為には、、ブロック内のコマンドの送信先をfunctionの実行時に指定しないといけない筈で、土屋がサンプルに追加したaboutを使った方法では上手く機能していないと思います（実際ローカルでは上手く動いて無い）。

**Comment by t-tutiya** [comment]
擬似コードですがこういう感じです。

#※１
create :ImageControl ,
       id: :char_icon,
       file_path: "./test/0104_03.png", x_pos: 0, y_pos: 0, 

define :char1 do
  #※２
  create :ImageControl ,
         id: :char_icon,
         file_path: "./test/0104_03.png", x_pos: 0, y_pos: 0, 
end

char1 do
  #※２のイメージに適用されて欲しい
  move_line x: 600, y: 300,   count:0, frame: 60, start_x: 0,   start_y: 0
end

コードとして表示するのどうやるの？

**Comment by t-tutiya** [comment]
ん、あれ、なんか勘違いしてるのかな。ちょっと弄る

**Comment by t-tutiya** [comment]
例えばこういうコードが動くのでも、目的は果たせると思っています。

#※１
create :ImageControl ,
       id: :char_icon,
       file_path: "./test/0104_03.png", x_pos: 0, y_pos: 0, 

define :char1 do |&block|
  #※２
  create :ImageControl ,
         id: :char_icon,
         file_path: "./test/0104_03.png", x_pos: 0, y_pos: 0, 
  block.call
end

char1 do
  #※２のイメージに適用されて欲しい
  move_line x: 600, y: 300,   count:0, frame: 60, start_x: 0,   start_y: 0, target: :char_icon
end

**Comment by t-tutiya** [comment]
んむむ……。これって現行の仕様では実現できないのかな……

**Comment by t-tutiya** [comment]
土屋の動いて欲しい形でひとまずプッシュしました（サンプルスクリプトが動かなくなっていますすみません）。ご意見求む。

**Comment by aoitaku** [comment]
> コードとして表示するのどうやるの？

\`\`\` （バッククォートを3つ）でくくるとコードになります。

\`\`\`
ここにコードを書く
\`\`\` 

Ruby のシンタックスハイライトをきかせたいときは

\`\`\`ruby
ここにコードを書く
\`\`\`

でできます。

**Comment by t-tutiya** [comment]
さんきゅーすー。
再修正した

**Comment by t-tutiya** [comment]
ここまで来ると、どんなコマンドであろうと、ブロック部はブロック式のまま保持して、コマンドが処理されるタイミングで実行時評価すればいいような気がしてきた（できるかどうかわかんないけど）

**Comment by RPGP1** [comment]
理想的な仕様について質問です。
以下のシナリオに於いて、各々のmove_lineが何に対して動作するのか、若しくはエラーが出るのか、教えて下さい。

```ruby
#※1
create :ImageControl,
    id: :char_icon,
    file_path: "./test/0104_03.png", x_pos: 0, y_pos: 0,
#※2
create :ImageControl,
    id: :char_icon,
    file_path: "./test/0104_03.png", x_pos: 0, y_pos: 0,
#※3
create :ImageControl,
    id: :char_icon2,
    file_path: "./test/0104_03.png", x_pos: 0, y_pos: 0,

define :char1 do
  #※4
  create :ImageControl,
      id: :char_icon,
      file_path: "./test/0104_03.png", x_pos: 0, y_pos: 0,
  #※5
  create :ImageControl,
      id: :char_icon3,
      file_path: "./test/0104_03.png", x_pos: 0, y_pos: 0,
  #※6
  create :ImageControl,
      id: :char_icon,
      file_path: "./test/0104_03.png", x_pos: 0, y_pos: 0,
end

char1 do
  #＊1
  move_line x: 600, y: 300, count: 0, frame: 60, start_x: 0, start_y: 0
  #＊2
  move_line x: 600, y: 300, count: 0, frame: 60, start_x: 0, start_y: 0, target: :char_icon
  #＊3
  move_line x: 600, y: 300, count: 0, frame: 60, start_x: 0, start_y: 0, target: :char_icon2
  #＊4
  move_line x: 600, y: 300, count: 0, frame: 60, start_x: 0, start_y: 0, target: :char_icon3
end

#＊5
move_line x: 600, y: 300, count: 0, frame: 60, start_x: 0, start_y: 0
#＊6
move_line x: 600, y: 300, count: 0, frame: 60, start_x: 0, start_y: 0, target: :char_icon
#＊7
move_line x: 600, y: 300, count: 0, frame: 60, start_x: 0, start_y: 0, target: :char_icon2
#＊8
move_line x: 600, y: 300, count: 0, frame: 60, start_x: 0, start_y: 0, target: :char_icon3
```

**Comment by t-tutiya** [comment]
■現状想定している仕様（未実装分も含む）

・ツリー上に同一ＩＤのコントロールが複数ある場合（１：デフォルト）→子要素ツリー探査時に最初に発見したコントロールに送信して終了
・【未実装】ツリー上に同一ＩＤのコントロールが複数ある場合（２：オプション設定によるブロードキャスト）→子要素ツリー内のＩＤが同じすべてのコントロールに送信する
・functionに設定されたブロック引数内のコマンド群は、そのfunctionで定義されたコマンド群をスコープ対象として送信される。
・

■質問への回答

＊１→現状仕様では想定していない（実装的には恐らく※４に送信される）。このままでも良い気がするけど、どうしようかな……

＊２→※４

＊３→送信先が見つからずエラー

＊４→※５

＊５→現状仕様では想定していない（実装的には恐らく※１に送信される）

＊６→※１

＊７→※３

＊８→※５（これは実行されたchar1がツリーに連結されているから。ただ、これが挙動として好ましいのかわからない）

**Comment by t-tutiya** [comment]
もしかしたら、コマンドにtargetを指定しない場合、子要素全てに向かって送信し、どこかが受け取ったらその時点で終了する、というのがあるべき実装なのだろうか？

**Comment by RPGP1** [comment]
今、自分が先程書いたコードを実行して確認したのですが、
＊1と＊5は現状ではエラーが出ます。

これはmove_lineコマンドが、＊1ではファンクションコントロールに、＊5では最上位コントロール(Rag)に対して送られる為です。

**Comment by RPGP1** [comment]
コマンドのtargetについては別Issueで話し合いましょう

**Comment by t-tutiya** [comment]
>これはmove_lineコマンドが、＊1ではファンクションコントロールに、＊5では最上位コントロール(Rag)に対して送られる為です。
え、あ、そっか。でも挙動としては現状が正しい（target:anonymousのコマンドは、そのコマンドが格納されているコントロールへ送信されるのが正し）。

**Comment by t-tutiya** [comment]
>コマンドのtargetについては別Issueで話し合いましょう
はーい

**Comment by RPGP1** [comment]
>挙動としては現状が正しい

分かりました。では、残るは＊8だけですね。

**Comment by t-tutiya** [comment]
考えたのだけど、functionは（スコープを限定する作用はあるものの）あくまでマクロ展開なので、上記コードの場合root直下に
:char_icon
:char_icon
:char_icon2
FuntionControl
  :char_icon
  :char_icon3
  :char_icon
というツリーが構築されるので、ここにrootからtareget: :char_icon3のコマンドが送信された場合、※５に送信されるのが正しい、としよう。

**Comment by RPGP1** [comment]
これで決定ですね。

**Comment by RPGP1** [comment]
すいません。少し考えてみたのですが、
FunctionControl内だけにスコープを限定してしまうのは良くないように思えてきました。

それをすると、下のコードが動かなくなります。

```ruby
create :ImageControl, id: :image1, file_path: 'test.png', x_pos: 0, y_pos: 0

define :move_image1_right do
  move_line :image1, x: 100, y: 0, count: 0, frame: 60, start_x: 0, start_y: 0
end

define :move_image1_down do
  move_line :image1, x: 0, y: 100, count: 0, frame: 60, start_x: 0, start_y: 0
end
```

関数を使って何を表現したいのかを理解していないのですが、例えば #30 などを見る限り、「関数内で生成した以外のコントロール」をtargetにコマンドを送ることが目的に入っているようには思えます。
ならば、スコープの限定は使えないのでは無いでしょうか。


しかし確かに、同一IDのコントロールが複数存在し、それらを区別しなければならない場合も有るとは思います。そこで、YIELD(の様な何か)を実装しようと試みています。

次のプルリクでスコープの実装が消えるだろうと考えてますが、こういう経緯だということを念頭に読んで頂けると助かります。

**Comment by RPGP1** [comment]
```ruby
create :ImageControl, id: :image1, file_path: 'test.png', x_pos: 0, y_pos: 0 do
  define :func do
    move_line x: 100, y: 100, count: 0, frame: 60, start_x: 0, start_y: 0
  end
end

create :ImageControl, id: :image2, file_path: 'test.png', x_pos: 0, y_pos: 0 do
  func
end
```

上のシナリオで、func内のmove_lineは:image1と:image2のどちらに作用するべきだと思いますか？

**Comment by t-tutiya** [comment]
・んーあー確かにそうか！
・関数はマクロ展開としても機能して欲しい（というか実質マクロ展開の筈）ので、展開された同一階層上にコマンドを送信できない場合実用にならないです。仰る通り。
・設計的にも、関数呼び出しにブロックが付与されていた場合、関数定義側でＹＩＥＬＤ（の様な何か）が呼び出された所でブロックの中身が実行されるのが正しい気がする－。

**Comment by RPGP1** [comment]
プルリクしました #34

**Comment by t-tutiya** [comment]
改めてコード読んでたんだけど、いやあ、我々（というか主にハイド君）は相当面白い物を作っているな！ｗ

**Comment by RPGP1** [comment]
大分DSLっぽくなりましたねーw
個人的に、method_missingとかdefine_methodとか、evalとかsendとか、メタっぽいものを駆使して超絶拡張するのが大好きでして。

勝手に「黒魔術プログラミング」って読んでますw

**Comment by t-tutiya** [comment]
整理の為に一旦closeしますー。
