### ISSUE TITLE
「アイドル・モード」

### ISSUE THREAD

**Issue by RPGP1** [t-tutiya/tsukasa#3]
@idol_mode
というインスタンス変数が有りますが、これは
@idle_mode
では無いでしょうか？

今出先(学校)でスマホしか持ってないので、Issueを立てておきます。

ついでに質問なのですが、この変数の切り替えの基準は何でしょうか？
今のところ、
control_container.rbではキー入力待ちの間に、
module_drawable.rb/module_movable.rbではトランジションの間に、
falseになってますね。

wait系コマンドなどは対象外なのですか？(よく分かってなくてすいません)

**Comment by t-tutiya** [comment]
>@idol_mode
>というインスタンス変数が有りますが、これは
>@idle_mode
>では無いでしょうか？

ぎゃー！　そうです（コード書いてる時は綴りとか気にしないので……＞＜）

>ついでに質問なのですが、この変数の切り替えの基準は何でしょうか？
>今のところ、
>control_container.rbではキー入力待ちの間に、
>module_drawable.rb/module_movable.rbではトランジションの間に、
>falseになってますね。

>wait系コマンドなどは対象外なのですか？

・@idle_modeは、そのコントロールがなにかしらの処理を行っていることを上位層に示す為に使われるフラグで、毎フレーム#updateでtrueに設定され、各コマンドが必要に応じてfalseを代入します（現状ではtrueに代入し直す運用は考えていません。これメソッド化すべきなのかも）
・なぜこの処理が必要なのかというと、例えば「テキストレイヤで、全ての文字列のフェードインが終わってから（≒@idle_modeがtrueになるまで待ってから）ポーズ入力を受け入れたい時」というタイミングを取得するためです。＜これが、module_drawable/movableで使われる理由
・#wait_key_push_with_idol/#check_key_pushでfalseを設定しているのは、その次に来るwait_idolがidolモードをチェックしてwait状態を続行するかどうかを判定しているからです。
・逆に、wait系コマンドは純粋にコマンドリスト探索を中断するか、それとも続行するかのみを判断しており、@idle_modeはそのwait系コマンドの判断補佐をする役割を持っています。
・（余談）moveやtransのコマンドがリストから削除されたかどうかを判定することもできます（その場合はwait_commandを使う）が、whileループなどを使った場合moveコマンドなどは永久に残り続けるため、このようなロジックが必要になると考えています。

(よく分かってなくてすいません)

いえいえ、びっくりするほど直感的で無いロジックで動くコードなので、気軽に聞いて下さい。

**Comment by RPGP1** [comment]
詳しい返信ありがとです！

追加で質問させてください。
2つのキーチェックコマンドで、continueとend_frameが違うのはどうしてでしょうか？
一方でwait_idleを使うのでしたら、両方同じにはしないのですか？

**Comment by t-tutiya** [comment]
command_wait_key_push_with_idol
と
command_check_key_push　＋　wait_idol
が同じなのでは？という質問でしょうか？

これ、それぞれ役割が違いまして、
command_wait_key_push_with_idol
・idol or キーが入力されていれば終了

command_check_key_push
・キーが入力されない限りidolにならない
wait_idol
・idolならば終了

という風になっています。
前者が「キー入力がなくともそれ以前の全てのコマンドがアイドルを返しているのであれば良い」のに対して後者は「必ずキー入力を必要とする」形になっています。

複数のwait終了条件をorで取る為には１つのコマンドの中で完結しなければならないため、こういう形になっています。

こちらも参考にどうぞ
http://d.hatena.ne.jp/t_tutiya/20150507

**Comment by RPGP1** [comment]
ありがとうございます。よく見たらそうでした><
「子要素のコントロールが全てアイドル状態の時にキーが押された場合」と有ったので勘違いしてました。
これもコメントの修正時に直せば大丈夫そうです。

これが気になった理由ですが、
command_wait_key_push_with_idleとcommand_check_key_pushの「ポーズ続行状態」での返り値が、
前者は:end_frame、後者は:continueであったからです。
この違いが混乱を生んだのですが、説明を見て納得しました！


このIssueは閉じますね。

**Comment by t-tutiya** [comment]
あ、ちなみにこれも綴り修正してくれたらマージしますー

**Comment by RPGP1** [comment]
はーい！

**Comment by RPGP1** [comment]
プルリクしました^^
