### ISSUE TITLE
汎用ログテキストレイヤの実装検討

### ISSUE THREAD

**Issue by t-tutiya** [t-tutiya/tsukasa#30]
暫くコード書く暇ないかもなので、次に組みたいロジックについてメモっておきます。
下記コードはやりたいことをなんとなくスクリプト化した物。

・汎用ログテキストレイヤを作ろうと思っています。以下のコードは、chat_baloonを実行するたびにログレイヤにテキストウィンドウが一個ずつ登録されていくことをイメージしています。
・YYY_Containerは、ログの個々のテキストに対して付与されるロジックが含まれています（例えば、ボイスを再生するためのボタンアイコンを表示する機能とか）。現状では（汎用実装になってませんが）ValiableTextLayerがこれに相当します
・現状だと、chat_baloonの中のtextをYYY_Containerに送信する為には、chat_baloon内でtargetを指定するかaboutで囲むしかなく、これをどうしたものかちょっと悩み中。ご意見求む。
```ruby
create :XXXX_Container, id: :XXX_Window

define :chat_baloon
  #chat_baloonが実行されるたびに、XXX_WindowにYYY_Containerが生成されることを期待している
  create :YYY_Container, id: :YYY_baloon, target: :XXX_Window do
    create :CharContainer, id: :innter_char
  end
end

chat_baloon do
  #以下のコマンドはYYY_Containerに送信されることを期待している
  #YYY_Containerではtextコマンドを加工し、innter_charに再送信する（この処理がそもそもおかしいのかも）
  text "test"
  line_feed
  text "test"
  line_feed
  text "test"
  line_feed
end

pause

chat_baloon do
  #二つ目のYYY_Containerを生成し、そこにコマンドが送信されることを期待している
  text "test"
  line_feed
  text "test"
  line_feed
  text "test"
  line_feed
end

pause
```

**Comment by t-tutiya** [comment]
ちょっと整理しておくと、
・現状の仕様では、あるコマンドが「どのコントロールの@command_list（あるいは@script_storage）上に格納されていて」「そこからどのコントロールに（:target指定で）送信されるのか」が重要
・funcitonのブロックによる追加コマンド群（これ名称欲しいな）は、実用上、そのfunctionが実行したコマンド群（が、生成したコントロール）に対して送信されて欲しい（現状はFunctionControlを介してスコープを限定することによって実現）。ただし、コントロールを生成しない場合もあるので注意。
・上記の場合は、funcitonのブロックによる追加コマンド群の送信先コントロールを変更したい。現状ではaboutで囲むしかない（試して無いが、デフォルトの送信先を変更してもよい）
　課題１：これを簡潔な記述で実現できないか（aboutもchengeも書きたく無い）
　課題２：そもそも、コマンドを上位コントロールがフックするもっと簡潔な方法が必要なのか？
　　・例えば、ValiableTextContainerの下にCharContainerがあり、上位からtextが送信されて来た場合に、自動的にValiableTextConatinerがそのコマンドをフックできる仕組みが必要なのか？
　　・あるいは、この場合は親子関係を作るのではなく、ValiableTextContainerがCharContainerを継承するべきなのか？

**Comment by t-tutiya** [comment]
転載しておきます。functionの中でdefault_classを変更すれば、土屋のやりたいことが出来るんじゃないのかという話。

>targetの指定が無い時について。
>(但し、default_classが存在するコマンドは、実質的にtarget指定が有るのと変わらないので除く。
>そういったコマンドで問題が発生した時は、default_classの指定が不適だと言えるでしょう。)

あ、そうか、ならこうあるべきなのか

```ruby
create :XXXX_Container, id: :XXX_Window

define :chat_baloon
  #chat_baloonが実行されるたびに、XXX_WindowにYYY_Containerが生成されることを期待している
  create :YYY_Container, id: :YYY_baloon, target: :XXX_Window do
    create :CharContainer, id: :innter_char
  end
　change_default_target　change_default_target: :CharContainer, id; :YYY_Container
end

chat_baloon do
  #以下のコマンドはYYY_Containerに送信されることを期待している
  #YYY_Containerではtextコマンドを加工し、innter_charに再送信する（この処理がそもそもおかしいのかも）
  text "test"
  line_feed
  text "test"
  line_feed
  text "test"
  line_feed
end

pause

chat_baloon do
  #二つ目のYYY_Containerを生成し、そこにコマンドが送信されることを期待している
  text "test"
  line_feed
  text "test"
  line_feed
  text "test"
  line_feed
end

pause
```

**Comment by RPGP1** [comment]
「#29 functionにブロックを付与したい意図について」とその解決案「#34 関数内のみで使える_YIELD_コマンドを実装」で、この問題も解決できたのではないでしょうか？

**Comment by t-tutiya** [comment]
出来たと思われる。後日検証します。

**Comment by t-tutiya** [comment]
整理の為に一旦closeしますー。
