### ISSUE TITLE
コマンドのtargetの動作について

### ISSUE THREAD

**Issue by RPGP1** [t-tutiya/tsukasa#31]
全てのコマンドには、キーワード引数を通してtargetの指定が可能です。
その機構について整理し、最終的な使用を決定することを目的に、このIssueを立ち上げます。

**Comment by RPGP1** [comment]
先ずは、targetが指定された時について。

**Comment by RPGP1** [comment]
コマンドがコントロールに送られた時(シナリオのルートではRag、aboutなどに囲まれていると別のコントロールに対して送られる)、
targetのIDが最初に見つかるまで、@control_listの先頭から順にチェックしていく。

```
0.  :root_control
1.    :control1
2.    :control2
3.      :control1
4.      :control3
5.    :control3
```

というツリーの0に対してコマンドが送られた場合、
`:control1`と指定すると1に、
`:control2`と指定すると2に、
`:control3`と指定すると4に格納される。

**Comment by RPGP1** [comment]
私の直感としては、「`:control3`と指定したら5に格納されるべきでは？」と思わなくもない…。上手く説明ができないが、
```ruby
  Const1 = 1
  module Const2
    Const1 = 3
    Const3 = 4
  end
  Const3 = 5
  
  p Const3 #=> 5
```
となる事に近い感覚かもしれない。

**Comment by t-tutiya** [comment]
・んー、まあそれは確かにそうかもしれないけど、ツリーを再帰で探査する場合はL4が先にヒットするんじゃないかなあ。
・とはいえ、送信元から確かに一番階層が近い所にヒットするのが正しい気がしなくもない。
・そもそもコマンドを上位から送信するたびにツリーを全探査するのが正しいのかもまだわからない（そこまで複雑なＵＩを構築してないから）

→現状は今のロジックを踏襲して、他の仕様上おかしいとなったら再検討しましょう

**Comment by RPGP1** [comment]
分かりました。
階層が浅い方を優先的にヒットさせることもできますので、仕様変更の時はやります。

**Comment by RPGP1** [comment]
targetの指定が無い時について。
(但し、default_classが存在するコマンドは、実質的にtarget指定が有るのと変わらないので除く。
そういったコマンドで問題が発生した時は、default_classの指定が不適だと言えるでしょう。)

**Comment by t-tutiya** [comment]
補足
・change_default_targetコマンドでdefault_classを変更することができる
・default_classのディスパッチテーブルは全てのコントロールがローカルで所有する（@control_default）

**Comment by t-tutiya** [comment]
>階層が浅い方を優先的にヒットさせることもできますので、仕様変更の時はやります。
ちなみにこれってどういう探査になります？

**Comment by RPGP1** [comment]
>>階層が浅い方を優先的にヒットさせることもできますので、仕様変更の時はやります。

>ちなみにこれってどういう探査になります？

コマンドを受けたコントロールを第0階層とし、子コントロールへ探査するように命令する時に、自分が第何階層か教えるのです。
子コントロールは、それを基に自分の階層を把握し、見つかったコントロールと共にその値を親コントロールに返します。
そうすれば、第0階層のコントロールのもとに、「指定したIDのコントロール」と「その階層」両方の情報が集まる筈です。

**Comment by t-tutiya** [comment]
あー、なるほど
でもそれって全探査になるよね（今だと見つかった時点で探査が終了する）。まあ、別にいいのかなあ……。

文字一個レベルまでコントロール化してるので、毎回全部探査するのはコストが高すぎる気がしなくもない（本当はidolを全部辿ってるのもやりたくない）。まあこれは検討事項で

**Comment by t-tutiya** [comment]
ごめん、誤操作で一個スレッドを削除ｊしてしまった気がするんだけど、どこに消えたのかがわからない

**Comment by RPGP1** [comment]
はい。私もそれが問題だと思います。

**Comment by RPGP1** [comment]
より良いロジックが思いつき次第ここに載せます。

**Comment by RPGP1** [comment]
targetの指定が無い時について。
(但し、default_classが存在するコマンドは、実質的にtarget指定が有るのと変わらないので除く。
そういったコマンドで問題が発生した時は、default_classの指定が不適だと言えるでしょう。)

**Comment by t-tutiya** [comment]
補足
・change_default_targetコマンドでdefault_classを変更することができる
・default_classのディスパッチテーブルは全てのコントロールがローカルで所有する（@control_default）

**Comment by RPGP1** [comment]
>補足

そうですね。

**Comment by RPGP1** [comment]
現在、コマンドを受けたコントロール自身が格納しますが、
それについて

>もしかしたら、コマンドにtargetを指定しない場合、子要素全てに向かって送信し、どこかが受け取ったらその時点で終了する、というのがあるべき実装なのだろうか？

と話されていました。

**Comment by t-tutiya** [comment]
>もしかしたら、コマンドにtargetを指定しない場合、子要素全てに向かって送信し、どこかが受け取ったらその時点で終了する、というのがあるべき実装なのだろうか？

ごめんなさい、これは間違い。少なくとも現状の仕様では、
・コマンドにtargetを指定しない場合自分自身に送信する
が正しいです。

**Comment by RPGP1** [comment]
…つまり、現状のままで正しいと言う事ですか？

**Comment by t-tutiya** [comment]
>targetの指定が無い時について。
>(但し、default_classが存在するコマンドは、実質的にtarget指定が有るのと変わらないので除く。
>そういったコマンドで問題が発生した時は、default_classの指定が不適だと言えるでしょう。)

あ、そうか、ならこうあるべきなのか

```ruby
create :XXXX_Container, id: :XXX_Window

define :chat_baloon
  #chat_baloonが実行されるたびに、XXX_WindowにYYY_Containerが生成されることを期待している
  create :YYY_Container, id: :YYY_baloon, target: :XXX_Window do
    create :CharContainer, id: :innter_char
  end
　change_default_target　change_default_target: :CharContainer, id; :YYY_Container
end

chat_baloon do
  #以下のコマンドはYYY_Containerに送信されることを期待している
  #YYY_Containerではtextコマンドを加工し、innter_charに再送信する（この処理がそもそもおかしいのかも）
  text "test"
  line_feed
  text "test"
  line_feed
  text "test"
  line_feed
end

pause

chat_baloon do
  #二つ目のYYY_Containerを生成し、そこにコマンドが送信されることを期待している
  text "test"
  line_feed
  text "test"
  line_feed
  text "test"
  line_feed
end

pause
```

**Comment by t-tutiya** [comment]
>…つまり、現状のままで正しいと言う事ですか？

正しいです申し訳ない。「functionにブロックを付与したい意図について」で定義された物でＯＫです

**Comment by RPGP1** [comment]
なるほどです。
汎用ログテキストレイヤについては、これから扱います。

**Comment by RPGP1** [comment]
少し話題が変わりますが、遠くないのでIssueをReopenして書きます。
targetの指定についてです。

現在、全てのコマンドでtargetの指定が可能ですが、それをキーワード引数にしているのは何故ですか？

aboutコマンドの指定が変更されてテストシナリオがエラーを出すようになっていたので、自分で戻そうと考えたのですが、少し気になったのでココに書きます。


```ruby
#現在のaboutの使い方
about target: :there do
  #commands
end

#私の思うaboutの使い方
about :there do
  #commands
end
```

動作としては全く問題ありませんが、より自然言語に近いと書きやすくないでしょうか？
(ノベルゲームシナリオを書く人が何を望んでいるかが分からないので、不要ならバッサリ斬って下さい。)

```ruby
#おまけです。こんな風に書けたら面白いかも知れません(?)
move_with_skip :straight, :control, from: [0, 0], to: [400, 300], in: 1.sec
```

**Comment by t-tutiya** [comment]
あ、確かにそうですね。現在の仕様ではキーワード引数でなければならない積極的な理由はありません。
以前は全部optionの中にいれていたのですが、targetだけは意味合いが違う（そもそもコマンドが受け取る引数ではない）ので分離したのでした。
うん、これやめよう。そのほうがaboutを自然に書けますね。

moveの記述方式についてもちょっと面白げ。これまではDTLの仕様を引きずっていて、引数内にruby式を書く事は想定してなかったのだけど、確かに今ならその方が可読性が高いね。その方向性も考えよう。

**Comment by RPGP1** [comment]
それでは、targetの扱いを通常の引数にし、テストシナリオも修正しますね。
他のコマンドの可読性向上は、コマンド別の小規模な修正群になりそうなので、仕様が安定してからにしましょう。

**Comment by t-tutiya** [comment]
ありがーです。これはキータイプが減って助かる予感！
