### ISSUE TITLE
script_compilerのimpl呼び出しについて

### ISSUE THREAD

**Issue by t-tutiya** [t-tutiya/tsukasa#35]
思いついた時に改善案を書いておきますー。気がついたら自分で実装するかも。

impl_で始まるコマンドメソッドを生成するヘルパーメソッドがいくつかあるのだけど、これもっと上手く書けない物かと思っている。

・基本的には全てのコマンドが「無名オプション（＝コマンド名がキー名になる物）」「送信先ターゲット」「ハッシュ」「ブロック」を受け取れる
・だが、コマンドごとにこれらのうちいらない物を受け取ったらパースの前にエラーを出るようにしたい
　・この「どの要素を受け取るのか」も引数で設定出来ない物か。
・（将来的には、キーワード引数名が間違っている場合もエラーにしたい）

**Comment by t-tutiya** [comment]
あと、今コマンドによってブロックのパースが「最初に評価してcommandオプション内に入れる物」と「ブロックのまま保持してコマンドの実行字に評価する物」があると思うのだけど、問題がなければこれは全部後者に統一したい。ブロックの中に書き込んだruby式が、そのコマンドの実行時に評価される事が保証されると、もうちょっと取り回しがしやすいように思う。

**Comment by t-tutiya** [comment]
ブロック部のブロック化（意味わからんな）処理を実装してみました。
なにがやりたいのか示したくてプッシュしたけど、いろんな所がバグって動いてません。
週末までに時間取れたら直しますー

**Comment by RPGP1** [comment]
見ました^^

ヘルパーメソッドについては概ね賛成です。現在の仕様で直接的な問題は無いかと思いますので、焦らずに考えて、使いやすいモノを作りましょう。

ブロック化については、少し迷っています。ブロックの"クロージャ"としての機能が邪魔にならないかな、予め展開しておいた方が実行時の負担軽減になるかな…等と考えてみたり。ただ、実行時展開の方が挙動が想像しやすいというのも納得できます。ですから、取り敢えず実装してみて、問題が有ったら戻しましょう。

script_storageに何を格納するのか、といった部分まで考えるのなら、もう少し仕様を練った方が良いかもしれません。上手く言葉に出来ませんが、コマンドを配列に入れていることで、先頭から順に取り出すという事が容易になっている側面を感じます。ブロックにするのなら何を用いてコマンド毎に区切るのか、そもそも区切りが必要なのか、コマンド配列の問題点は何か…。私と土屋氏の間に、まだ確固たる設計が共有できてない様に感じます。

また沢山のIssueを立てて話し合いましょう！


あとそれから、バグが有る(と判明している)コードはmasterにプッシュせず、branchを切ってみてはどうでしょう？不可避のバグだった場合の処理が楽になります。

**Comment by t-tutiya** [comment]
あ、ツイート読み逃した。上のバグの部分修正しましたです（テキストレイヤは治ってない）

>取り敢えず実装してみて、問題が有ったら戻しましょう。
はーい

>コマンドを配列に入れていることで、先頭から順に取り出すという事が容易になっている側面を感じます
実はそうなんだよね。ただ、やるのであれば全部配列にするか、全部procにするかじゃないと、コードの位置によって配列だったりprocだったりして、これはこれで保守しにくいようにおもいます。

>バグが有る(と判明している)コードはmasterにプッシュせず、branchを切ってみてはどうでしょう？
github本当に知らないんで、そもそもブランチやフォークがなんなのかもわかってないのよねｗ　来月くらいから多少余裕ができるので、改めて調べてみますー。

**Comment by t-tutiya** [comment]
あ、ごめん、なんか誤解があるな。option[:commands]を全廃してoption[:block]に統一したいというだけで、script_storageやcommand_listにブロックを格納したいという話ではないです（それは配列のままでいい）。

**Comment by RPGP1** [comment]
あ。誤解してました(笑)

では、お互いがんばりましょう。

**Comment by t-tutiya** [comment]
・char_rendererが機能するようにしました。
・それですみません、現在入れ子になっているブロック内でのYIELDが機能しません
・（具体的にはscenario_function.rbがL56の_YIELD_を無限再帰呼び出しして終了している。これ例外でないのわかりにくいね）
・原因は、全てのブロックが必ず実際の評価タイミングが来るまで展開しないため、@arg_blockが適切なブロックを保持していないからです。
・_YIELD_を正式にコマンド化してしまって、function実行時に付与しているブロックを適切に伝搬できればいいのかなと思ったけど、上手く治せなかったので一旦ここまでにしましたー。

**Comment by t-tutiya** [comment]
忘れてた。defineのタイミングがギリギリまで遅延するようになった為、L48のfunc呼び出しも失敗します（この時点でまだfuncが定義されていない為）。これについてはスコープや関数定義タイミングをどうするかという別の問題がはらんでいそう。ＤＳＬ作るのって大変なんだなあ……。

**Comment by t-tutiya** [comment]
土屋の想定する挙動になるように修正してみたんですが、スクリプトの記述が超面倒になりましたｗ

```ruby
define :func2 do |arg_block|
  create :ImageControl, 
         :file_path=>"./sozai/button_normal.png", 
         :id=>:normal2,
         :yield_block => arg_block[:yield_block] do |arg_block|
   
   _YIELD_ &arg_block[:yield_block]
   
  end
end

#functionを実行後、ブロック内のコマンドを実行する
#TODO：aboutではなく、func2の引数で送信先を指定できないものか
func2 do
  move_line x: 600, y: 300,   count:0, frame: 60, start_x: 0,   start_y: 0
end
```

これもうちょいなんとかならんもんか……！　本日時間切れ

**Comment by t-tutiya** [comment]
メモ：send_commandする時に隠しパラメータでyieldを添付すればいいのかな？

**Comment by t-tutiya** [comment]
できたーノシ

**Comment by t-tutiya** [comment]
・while対応した

・ifは条件式を評価した時点ではまだブロックが評価されていないので修正が必要。
・条件式の結果を下部に伝播してthen/elseコマンドが自身が持つブロックを評価＆実行するかどうかを判断し、ブロックが一個でも実行されたら残りを無視して終わるのかな（そうでないと、実行しないのに評価されるブロックが存在してしまう）

**Comment by t-tutiya** [comment]
あらかじめスクリプトを完全に配列化した方が、確かに実行時負担は低いし、移植性も高くなるのだけど、恐らく今のスタイルの方が開発効率が断然高いので、今回はこのアプローチで行きましょう。司エンジンのコンセプト実証が完了したら、次のメジャーバージョンアップで高移植性を検討する感じで（いつだよ）

**Comment by RPGP1** [comment]
お久しぶりです。
コードを解読しきったわけではありませんが、一週間かけて色々考えた中で感じた違和感をお話しします。
結論から言うと、コマンドに与えられる全ブロックを実行時評価することに反対です。

シナリオを記述していく上で、「表現されるべきコマンドの実行順」が再現されていないからです。
これは「関数がdefineされている筈なのに使えない」という問題に表れています。記述順を組み替えれば(それで良いかは取り敢えず放置します)再現できる物だけではなく、例えばIF文の中で定義しようとしてもできない状況です。

現状の配列で保持しておくことに問題が感じられず、またブロックで保持しておくことに利点が感じられない為、今のところは反対という訳です。

ブロックで保持しなければならない理由があるそうですので、その提示をお待ちしています。

**Comment by t-tutiya** [comment]
・ご意見感謝です。大まかにはDMした通りで、しばらくはこのままでいかせてください。もう少し考えてから結論を出そうと思います。
・今ぼんやり考えているのは、実行時評価タイミングを極限まで遅くする意味はあるかなと考えています。

例えば、下記コードを書いた際に、個々のpが実際にそのthen/elseブロックが評価された時に実行することが出来ます（現実問題としてこういうコードを書く事があるかは置く）。配列化の場合、then\elseを配列化した時にpが実行されてしまいます。

```ruby
IF 条件式 do
  THEN do
    p "then"
  end
  ELSE do
    p "else"
  end
end
```

また、関数呼び出し時の引数の伝搬（？？？）も全ブロック化した方が上手く回るように思っています。

・ちなみに、配列でやるなら全部配列にしたい（関数の付与ブロックも含めて一切ブロックで保持したくない）と考えています。逆に言えば、どちらかに統一できるなら構わないのかなと言う気もします。
・これについては6月後半に再検討したいと思います。すみませんがよろしくです。

**Comment by t-tutiya** [comment]
まあ、最適化された実装になっていれば、全ブロック化から全配列化に変更するのはそんなに大変ではないと思いますんで、現状のコードを作り込んでもムダにはならないと思ってます。まあ、ムダになってもいいじゃない（爆）。

**Comment by RPGP1** [comment]
なるほど…コマンドにRuby処理を組み合わせるのですか。
そしてそれを実行時に評価する、と。

難しいですね。面白い。

ムダになることは気にしてません(笑) これまでも沢山のコードを無駄にしてますしw

**Comment by t-tutiya** [comment]
>ムダになることは気にしてません(笑) これまでも沢山のコードを無駄にしてますしw

ありがとー＞＜

・今思いついたけど、例えばこういうことも出来るんじゃなかろうか

```ruby
IF 条件式 do
  THEN do
    define func_A do
      定義Ｘ
    end
  end
  ELSE do
    define func_A do
      定義Ｙ
    end
  end
end
```

つまり、実行時に定義する関数をスイッチできるのではないか（そういう作業が必要になるのかは置く）

・ただ、既に発生している「関数を呼び出した時に、（コード上先に書かれているにも拘わらず）その関数が定義されておらず、実行できない場合がある」という問題は確かにあって、これを解決する方法があるのか、あるいは解決する必要があるのか（例えば、ブロック内では関数定義できない物とする、という回避策もある）

**Comment by RPGP1** [comment]
その関数定義のスイッチは、必要になってくる機能だと思うのですが、THENやELSEのブロックの中にあるので、呼び出したい時に呼び出せない…。

**Comment by t-tutiya** [comment]
ん？　このif文が終わったタイミングで定義されるんじゃない？（今の実装ではダメかもしれんけど）

**Comment by RPGP1** [comment]
現在の実装では、IF文のブロックが評価されるまで関数は定義されないので、
IF文の後でも、トップレベルから関数を呼び出そうとするとエラーが出ます。

**Comment by t-tutiya** [comment]
>現在の実装では、IF文のブロックが評価されるまで関数は定義されないので、

あー、そっか……。
next_frameで１フレ送る手もある気がするけど、もっと上手い解決策がある気がする。
あと今気づいたけど、上のスイッチをやるんであれば別にrubyのif文でもいいねｗ

**Comment by RPGP1** [comment]
rubyのifも使えなくはないですが、条件式の実行を遅延させたければ、IFコマンドを使わざるを得ません。

**Comment by t-tutiya** [comment]
だよねー。検討していきましょー。そして今日も執筆－。

**Comment by RPGP1** [comment]
ファイトです^^

**Comment by RPGP1** [comment]
突然ですが、
Fiber(コルーチン)を使ってみませんか？

**Comment by t-tutiya** [comment]
・土屋のfiber嫌いについては下記２エントリを参照してくださいｗ

http://d.hatena.ne.jp/t_tutiya/20150218/1424219862
http://d.hatena.ne.jp/t_tutiya/20150208/1423359577

・状態遷移機械（司エンジンではコントロール）の処理をfiberで制御すると、fiberの仕様にフレームワークの設計が束縛されてしまうのではないかというのが土屋の考えです。
・ただ、これまでと同様土屋の発想の範囲内でそう思っているというだけなので、設計の提案は常に歓迎しますー＞＜ｂ

**Comment by t-tutiya** [comment]
ちなみに上記エントリの４要件は古くなっていて、最新はこれ

http://d.hatena.ne.jp/t_tutiya/20150511/1431327733

**Comment by t-tutiya** [comment]
なぜcreate時にコマンドブロック内のdefineが実行されないのかずっと疑問に思っていたのだけど、実装がバグってた。これで旧仕様との互換性を満たしたと思います。

**Comment by RPGP1** [comment]
むむむ…コミットが増えて、ちょっと追えなくなってきました><
途中で仕様の変更が何度かあったり、一塊の変更がコミット単位で表現されていなくて…(T_T)

私のリポジトリが、最初に\_YIELD\_が実装されたところのまま保持されているので、そちらの方で全ブロック化の別のアプローチを目指してみます。
直ぐには出来ませんが…完成したら見てください。

**Comment by t-tutiya** [comment]
githubの使い方がよくわかってなくて変になってしもうた＞＜

>私のリポジトリが、最初に_YIELD_が実装されたところのまま保持されているので、そちらの方で全ブロック化の別のアプローチを目指してみます。
>直ぐには出来ませんが…完成したら見てください。

りょかーいです。
しばらくデモ作成に必要なコードを決め打ちでコミットしちゃいますが、あんまり気にしないでねーノシ

**Comment by t-tutiya** [comment]
疲れた頭でコードを書いてはいかんな俺……。

ようやく修羅場を抜けたのでコードを確認したら、ＹＩＥＬＤ周りのコードが、動いてはいるが明らかに設計がおかしいことに気付きました。

・YIELDをコマンド化したつもりだったがしていなかった（致命的）
・send_command系に追加の引数が必要だと考えていたが必要なかった
・コマンドブロックと関数ブロックを複雑に入れ替える必要があると考えていたが必要なかった

などなど。全部直したら改修前のコードからの最低限の修正になったと思います。
IF系を含め、ハイド君のオーダーを満たした上で全ブロック化を実現できているのではないかと思いますんで、時間がある時にでもチェックしてみてください～ノシ

**Comment by t-tutiya** [comment]
整理の為に一旦closeしますー。
