### ISSUE TITLE
メモ:スクリプトファイルの切り替えについて

### ISSUE THREAD

**Issue by t-tutiya** [t-tutiya/tsukasa#36]
・if/when-caseの修繕の次に作ろうと思ってるのは、スクリプトファイルの切り替え。
・今は現在のスクリプトファイルを読みきったあと、次のファイルが指定されていればそれを読むのだけど、やはり強制的に切り替えたいときもあるように思う。
・現状でもrootの@script_storageの中身をごっそり入れ替えれば動く気がしていて、ひとまずそのコマンドを作るつもり。
・ただ、これだと各コントロールの中にかなりゴミが残る気がしている（特にCharContainer)
・もしかしたら、各コントロールはデストラクタ的なコマンド列を持っていて、適切なタイミングで呼び出す必要があるのかも？
・また、コンストラクタコマンド列も用意して、初期化パラメータはそこに渡すべきなのかも。
・吉里吉里でいう画像レイヤー(必要に応じて任意の画像ファイルを設定する概念レイヤ）を実装するときに、パラメーターの更新を汎用化させるにはどうするべきなのかも悩み中

**Comment by t-tutiya** [comment]
メモ:@command_listのクリアも必要

**Comment by RPGP1** [comment]
お久しぶりです。
コードを解読しきったわけではありませんが、一週間かけて色々考えた中で感じた違和感をお話しします。
結論から言うと、コマンドに与えられる全ブロックを実行時評価することに反対です。

シナリオを記述していく上で、「表現されるべきコマンドの実行順」が再現されていないからです。
これは「関数がdefineされている筈なのに使えない」という問題に表れています。記述順を組み替えれば(それで良いかは取り敢えず放置します)再現できる物だけではなく、例えばIF文の中で定義しようとしてもできない状況です。

現状の配列で保持しておくことに問題が感じられず、またブロックで保持しておくことに利点が感じられない為、今のところは反対という訳です。

ブロックで保持しなければならない理由があるそうですので、その提示をお待ちしています。

**Comment by t-tutiya** [comment]
ご意見感謝です。大まかにはDMした通りで、しばらくはこのままでいかせてください。もう少し考えてから結論を出そうと思います。
今ぼんやり考えているのは、実行時評価タイミングを極限まで遅くする意味はあるかなと考えています。
ちなみに、配列でやるなら全部配列にしたい（関数の付与ブロックも含めて一切ブロックで保持したくない）と考えています。
これについては6月後半に再検討したいと思います。すみませんがよろしくです。

**Comment by RPGP1** [comment]
分かりました

**Comment by t-tutiya** [comment]
追記した

**Comment by t-tutiya** [comment]
スクリプトファイルの切り替えは以下の方式としました。
・breakでスクリプトファイルの末端に移動（その為にaboutを使う）
・ファイルの末端で分岐させてsetでスクリプトファイルを設定＆読み込む
これで回るのであれば@command_listをクリアする機構は無しで。一旦クローズします。
