### ISSUE TITLE
メモ：if文の実装案

### ISSUE THREAD

**Issue by t-tutiya** [t-tutiya/tsukasa#37]
・then/elsif/elseもコマンド化する
・ifコマンドでは条件式をeval_lamdaで評価し、結果の真偽値Ａを子要素に伝搬する（どうやるのかは知らぬ）
・thenコマンド：Ａ==trueなら自身に付与されたブロックをeval_blockで評価し、retrun :next_frameする
・elsifコマンド：条件式をeval_lamdaで評価し、真なら自身に付与されたブロックをeva_blockで評価し、retrun :next_frameする／偽ならretrun :continueで次のコマンドに進む
・elseコマンド：aboutのalias

これならif文を抜けた段階で、下位要素は全て評価が終わっているのではなかろうか（then/elsif/else以外のコマンドがif直下にある事を弾く手段が必要かもしれないけど）

**Comment by t-tutiya** [comment]
ん、あ、そっか。
```ruby
ifブロック（define文Ａを含む）
Ａの呼び出し
```
と@script_storageに積まれている時に
```ruby
ifコマンドを対象ターゲットに送信
Aを対象ターゲットに送信（しかしこのタイミングではＡが定義されていない為、call_functionが失敗する）
```
となる、のか？　がーん。ようやく理解した。勘違いしてたわ。
とはいえ、この場合は、
・if文が送信されることがそもそも間違っている（tokenがscript_storageから取って来たタイミングで処理されるべきなのではないか）
・定義されていないfuncが送信出来ないことがそもそも間違っている
の２つも検討対象にしたい。

**Comment by RPGP1** [comment]
定義されていない関数を弾いているのは、Control#commmand_call_function内だったと思います。
これは「今まさに実行しようとしているProcが無い場合にエラーを出す」といった動作です。

ここで弾かれることは至極自然なことであり、同時に不可欠ですから、見直すのはやはり「ブロック実行のタイミング」だと思います。

**Comment by t-tutiya** [comment]
あれ、そうなのです？ ごめん、ハイド君の考える「こういうコードが動かない筈」をここに貼っておいてもらえますか（今はロジック自体が死んでるから実行できないので）

**Comment by RPGP1** [comment]
「こういうコードが動かない筈」というのは、「動く筈なのに動かないコード」ということですか？
それでしたら、恐らく土屋さんの考えている物と同じだと思います。

```ruby
IF ->{'条件式'} do
  THEN do
    define :func do
    end
  end
  ELSE do
    define :func do
    end
  end
end

func
```

**Comment by RPGP1** [comment]
今調べてみましたが、control_container.rbとscript_compiler.rbの中で`Kernel#raise`が用いられているのは合計9件で

1. `Control#update`内で、`command_*`を実行した際の返り値が`:end_frame` or `:continue`でなかった場合
2. `Control#render`内で、`@float_mode`が`:right` or `:left` or `:none`でなかった場合
3. `Control#command_token`内で、`send_command`がコマンド送信先を見つけられず`false`を返した場合
4. `Control#command_call_function`内で、指定された関数名が`@@finction_list`の中に見つからなかった場合
5. `ScriptCompiler#_YIELD_`内で、実行すべきブロックがなかった場合(現在はコメントアウト中)
6. `ScriptCompiler`の`THEN`, `ELSIF`, `WHEN`, `ELSE`が不適切なタイミングで呼ばれた場合

です。

これらの中で、関数の呼び出しを弾く機能があるのは4だけです。
すなわち、`eval_block`の直前です。

**Comment by RPGP1** [comment]
command_tokenの見直しには反対ではありません。

**Comment by t-tutiya** [comment]
ありがとうです。検討します。少し遅くなるかもごめんなさいです。

**Comment by t-tutiya** [comment]
ひとまずテスト案をアップしました。scenario_test_if.rbで動作を確認できます。
コードを書く時間が昼休憩しかないので、文法がこなれていませんが、土屋がやりたいことはこういう感じです。
条件式を非ラムダにしたのは単に条件式の結果を下部に伝搬させるのが面倒だっただけで、こうしたいというわけではないです。ご意見求む。

**Comment by RPGP1** [comment]
> ・ひとまずテスト案をアップしました。scenario_test_if.rbで動作を確認できます。
> ・コードを書く時間が昼休憩しかないので、文法がこなれていませんが、土屋がやりたいことはこういう感じです。

見ました。

> ・試してませんが、現状だとif文をネストさせた場合に機能しないと思います。

IF文の条件式の評価結果を@test_if_resultという単一変数に代入しているから、そうなりますね。

> ・ただ、見た目がruby系になる必要は特にないので、このままでも構わないといえば構わないです。

ruby系になる必要は確かに無いですが、この文法のままにはしておきたくないですね。美しくないです。
やろうと思えばruby系の文法には出来るのですから、それ以上の物は目指しましょう。

あと、フレームを送るのには意味があるのでしょうか？

**Comment by t-tutiya** [comment]
>あと、フレームを送るのには意味があるのでしょうか？

あ、ないです。直すの忘れた。

**Comment by t-tutiya** [comment]
現状。入れ子に対応した（と思う）
```ruby
#! ruby -E utf-8

test_if ->{true} do
  test_then do
    define :func do
      pp "func then"
    end
  end
  test_else do
    define :func do
      pp "func else"
    end
  end
end

func

test_if ->{false} do
  test_then do
    define :func2 do
      pp "func2 then"
    end
  end
  test_else do
    test_if ->{true} do
      test_then do
        define :func2 do
          pp "func2 else then"
        end
      end
      test_else do
        define :func2 do
          pp "func2 else else"
        end
      end
    end
  end
end

func2
```
・現状では、残念ながら同じロジックではelsifやcase-whenが実装できない。

**Comment by t-tutiya** [comment]
整理の為に一旦closeしますー。
