### ISSUE TITLE
用語の統一について考えるスレ

### ISSUE THREAD

**Issue by t-tutiya** [t-tutiya/tsukasa#38]
スクリプトファイル記述時、rubyVMの評価時、内部コード変換時（？）、実行時など、司エンジンではゲームという超複雑なタイミング制御が必要なロジックを記述するためにあまり他では作らない（面倒だからね！）独特なアーキテクチャになっており、個々の状況について説明する用語も統一していません。

このスレでは、ディスカッション時に必要になる個々の用語や、コード内の名称統一などについて議論しましょう。

**Comment by t-tutiya** [comment]
ちなみになんですが（issueに書いている時は仕事したくなくて逃避している時です）、
ControlContainerというクラス名は形骸化していまして、
元々は単一の最小単位であるControlと、そのControlを子のチェインとして管理するControlContainerという２つのクラスを作っていたのですが、
途中で全てのControlは例外なく子のチェインを持つという仕様に変えたため、この２つは統合されました。
なのでxxxxContainerという名称は破棄しても良いかなとも思っています。

**Comment by RPGP1** [comment]
確かに、用語の定義を改めるべき規模になってきたようにおもいます。

やりすぎかもしれませんが、
「一般に共通した意味で使われる用語のみで、このプロジェクトにおける全ての用語を定義する」
なんてことをするのも有効かな、と。

以下、少し前に考えてみたものです。(仕様変更によって、一部正しくないかもしれませんが…)

名前と引数を構成要素とする、命令の最小単位が「コマンド」
シナリオファイルに書かれるのが「シナリオ」
シナリオを配列にしたものが「コマンド群」
call_functionにブロックで追加するシナリオが「追記」もしくは「追記シナリオ」
シナリオをコマンド群にすることが「展開」

Controlクラスと、それを継承したクラスが「コントロールクラス」
コントロールクラスのインスタンスが「コントロール」
Ragを頂点とし、@control_listで繋がれたコントロール全体が「コントロールツリー」
コントロールツリー中のあるコントロールから見て、@control_listに登録している別のコントロールが「子コントロール」
あるコントロールは、その子コントロールから見て「親コントロール」

**Comment by t-tutiya** [comment]
>Controlクラスと、それを継承したクラスが「コントロールクラス」
>コントロールクラスのインスタンスが「コントロール」
>Ragを頂点とし、@control_listで繋がれたコントロール全体が「コントロールツリー」
>コントロールツリー中のあるコントロールから見て、@control_listに登録している別のコントロールが「子コントロール」
>あるコントロールは、その子コントロールから見て「親コントロール」

これについてはこれで統一しましょう。

**Comment by t-tutiya** [comment]
以下については、土屋が普段使い（？）している用語に合わせさせてください。

シナリオ（スクリプト）
 ゲームを記述した物。コマンドから構成される。rubyのソースコードとして扱う。

コマンド
 命令の最小単位。名前と引数から構成されるruby式。
コマンド配列
　配列状態のコマンド。コマンドを配列に変換することは「展開」と呼称する。
関数ブロック
　関数呼び出し時に付与されるブロック引数。関数内部から_YIELD_で呼びだされる。
　これに対し、defineを含む通常のコマンドに付与されるブロック引数は「[コマンド名]ブロック」とする（例：defineブロック）
