### ISSUE TITLE
Control#command_check_key_pushのコメント

### ISSUE THREAD

**Issue by RPGP1** [t-tutiya/tsukasa#4]
Control#wait_key_push_with_idle と同じになってます…

**Comment by t-tutiya** [comment]
おーう……。実はコメントは結構適当になっています。うーん、来月くらいにまとめて直す事になりそう。

（余談）wait系は今用途ごとにメソッドを作っているのですが、これ非常にめんどくさいので、将来的にはwaitというコマンドを一個作り、オプションでwait条件を設定できるようにしたいと思っています。
・idle
・frame_count
・key_push
・skip
をorでチェック出来るとかなら、今あるコマンドを包括できる気がしています。

**Comment by RPGP1** [comment]
分かりました！

waitのその仕様は便利で良さそうですね^^
