### ISSUE TITLE
スクリプトリプレーサーの仕様を考えるスレ

### ISSUE THREAD

**Issue by t-tutiya** [t-tutiya/tsukasa#40]
>あおいたく

ツイッターで話していた、現状想定しているリプレーサーの仕様をアップしておきます。
ぼんやりとこう考えているというだけなので、なにかあれば提案歓迎します。

■ルール１：
・行頭が"@"であれば、二文字目以降を空白など含めて全てrubyコードとして出力する

```ruby
入力
@test 3
@   test  5,5 #@のあとに半角空白３個

出力
test 3
   test  5,5 #@のあとに半角空白３個
```
補足："@"は１文字以上の任意文字であることが望ましい

■ルール１－ａ：
・吉里吉里とは違い、@１行が１命令ではない（rubyコードとしてのパースはこの後で行う）。

```ruby
入力
@ create :ImageControl,
@   id: :test

出力
 create :ImageControl,
   id: :test
```
■ルール２：
・行頭が"//"の行はコメントとして無視する

補足："//"は1文字以上の任意文字であることが望ましい
補足：このように無視する行を複数作れるとより望ましい（例えば"//"と"||"の2つをコメント扱いするとか）

■ルール３：

・ルール１／２が適用されない行はヒアドキュメントと見なし、以下の処理を行う
　・textコマンドの引数に設定して出力
　・line_feedコマンドを出力

```ruby
入力

@pause
テスト文字列１
テスト文字列２

出力

pause
text "テスト文字列１"
line_feed
text "テスト文字列１"
line_feed
```
補足
・line_feedコマンドを出力するかどうか（あるいはline_feed以外の要素を出力するか）は任意に設定出来ると望ましい

■ルール３－ａ：

・ヒアドキュメントの中で"["～"]"で囲まれた部分は埋め込みコマンドとみなす。

```ruby
入力

テスト文字列１[pause]テスト文字列２[pause 2]

出力

text "テスト文字列１"
pause
text "テスト文字列２"
pause 2
line_feed #line_feedが出力されるのはここだけなので注意
```
補足

・埋め込みコマンド中の改行は認めない物とする（この制限、別に必要ないかな？）
・埋め込みコマンドの中で"[""]"を使う必要がある場合は、エスケープシーケンスにする（ただ、rubyの""/''のように、差し替え可能な括弧があると助かります。

**Comment by t-tutiya** [comment]
行頭@はインデントで代替できても良い気がした

**Comment by aoitaku** [comment]
あっ、書いてたら 2 ゲットしそこねた＞＜

ちょうどインデントで代替できるといいなあということを思っていました。インデント構造のパースはRubygemsにライブラリがあるので実装は簡単です。

**Comment by t-tutiya** [comment]
インデントでいってみようか。その方がモダンな構造な気がする。
ただ、プログラムの方はインデントでいいのだけど、コメントとヒアドキュメント部はプログラムを知らないライターさんが書く所なので、極力プレーンなテキストになるのが望ましいです。

**Comment by aoitaku** [comment]
ぼくもコメントとヒアドキュメント部はできるかぎりプレーンなテキストにすることに賛成です。

- インデントあり ： スクリプト
- インデントなし
  - 行頭@ ： スクリプト
  - 行頭// ： コメント
  - それ以外 ： ヒアドキュメント

こういう感じですかね。

埋め込みコマンド中の改行は、見た目上の改行が目的なら制限しなくても問題ないと思います。この場合は空白文字として扱うことになります。
Rubyのスクリプトとして改行が意味を持つようなもの（つまり複数行のRubyスクリプト）は多分ややこしくなると思うのでやめたほうがよさそうです。

**Comment by t-tutiya** [comment]
>こういう感じですかね。

おけおけです

>埋め込みコマンド中の改行は、見た目上の改行が目的なら制限しなくても問題ないと思います。この場合は空白文字として扱うことになります。
>Rubyのスクリプトとして改行が意味を持つようなもの（つまり複数行のRubyスクリプト）は多分ややこしくなると思うのでやめたほうがよさそうです。

あー、なるほど。それで行きましょう＞空白文字として扱う

**Comment by t-tutiya** [comment]
すいませんこれ考えたんですが、複数行に渡るスクリプト記述なのであればインデント or @を使うべきなので、やっぱり"["～"]"内の改行はナシにしたいと思います（括弧が閉じてなかったらsyntax error）。
　なので、リプレーサー自体はstaticな実装で、１行文のシナリオを受け取ったら機械的に変換して返す、という形になるんじゃないかな？　と思いますー。

**Comment by aoitaku** [comment]
りょうかいです！

**Comment by t-tutiya** [comment]
一個忘れてた。空行を「pause」にしたい（機械的に置換。複数空行は無い物として扱う）。
これで、テキスト処理は出来るかな……？

**Comment by aoitaku** [comment]
複数空行は空行一個とみなすっていう感じでしょうか。
一点気になるのはスクリプト行の後の空行をpauseにするかどうかですね（個人的にはスクリプト行の後の空行はpauseにならないほうが使いやすいような気がします）

**Comment by t-tutiya** [comment]
>複数空行は空行一個とみなすっていう感じでしょうか。

これ、多分この方が便利だと思うんだけど、リプレイサーが状態を持っていいのかというのが判断つかないな……（レスした時は、空行１個につき機械的にpauseにするつもりだった）。

>一点気になるのはスクリプト行の後の空行をpauseにするかどうかですね
>（個人的にはスクリプト行の後の空行はpauseにならないほうが使いやすいような気がします）

んー確かにそうだね……。でもこれも状態をもたないといかんよねえ。

どう思います？

**Comment by aoitaku** [comment]
今考えているリプレイサーの実装だと、最初にスクリプト部とテキスト部とにわけて、その後テキスト部のパースを一行ごと処理するようにしようと思っていますが、テキスト部のパース前に
- テキスト部に先行する空行をトリミングする
- 連続する空行を一つにまとめる
この二つをやってからテキスト部のパースを開始すれば状態を持たなくても大丈夫そうな気がします。

**Comment by t-tutiya** [comment]
あー、なるほど、。前処理があるのね。それで行きましょう！

**Comment by aoitaku** [comment]
∠ﾟワ^)☆ かしこまっ！

**Comment by aoitaku** [comment]
ひとまず gist に実装をアップしました。
https://gist.github.com/aoitaku/8ed49cb4b95bfb096519

あとでシナリオフォルダ内のソースを元に上記の形式のシナリオファイルを使って意図したとおりに変換できるか試そうと思っています。
試したものをexampleとして用意していっしょにgithubにリポジトリに入れる予定です。

**Comment by aoitaku** [comment]
そういえば github に別途リポジトリを作るのがいいのか、tsukasa のリポジトリ内にあるのがいいのか、ということを考えていませんでした。

個人的には独立したライブラリになっているほうが配布時に分離しやすくていいのかなーと思っています。利用するときに二箇所から持ってこないといけないのは手間になるので悩ましいところです。

**Comment by t-tutiya** [comment]
ありがとー！！！＞＜
うーん、ひとまず独立させておきましょうか。いずれは取り込んじゃうかも。
ちなみに、今の所はScriptCompilerがスクリプトファイルを読み込む時に、拡張子が".rb"であればそのまま解釈し、".tks"であればパーサーを通してから解釈する、という形にできないかと思っています。

**Comment by aoitaku** [comment]
了解です。それでは一旦独立したリポジトリを用意しますね。
