### ISSUE TITLE
Control#all_controls_idol?での処理量削減

### ISSUE THREAD

**Issue by RPGP1** [t-tutiya/tsukasa#5]
条件分岐に@idol_modeを使用せず、このメソッドを使用するのでしたら、

```ruby
  def all_controls_idol?
    @idol_mode &&= @control_list.all?(&:all_controls_idol?)

    return @idol_mode
  end
```

の方が処理が少なくなるのでは無いでしょうか？

**Comment by t-tutiya** [comment]
すみませんruby詳しくないのでall?なるメソッドがあるのを初めて知りました（引数の頭の"&"もわからない）。これって元コードと互換あるんですか？　ならこれで良いかなと思います。

**Comment by RPGP1** [comment]
このコードは、「完全な互換」は実現されていません。
自コントロールの@idle_modeがfalseであったり、子コントロールのall_controls_idle?が1つでもfalseを返したりすると、
その時点で実行をやめて、 return falseしてしまいます。
従って、all_controls_idle?が呼ばれないコントロールが存在しますが、代わりにその分だけ処理が少なくなります。

<以下、長い注釈です>

引数の`&'は、それに続くオブジェクトのto_procメソッドを呼び、その返り値をブロックとして渡します。
```ruby
method(&:name)
```
は、Symbol#to_procを利用して
```ruby
method do |item|
  item.name
end
```
と同じ動作をします。

次に`all?'です。
配列は[Arrayクラス](http://docs.ruby-lang.org/ja/2.1.0/class/Array.html)のオブジェクトですが、このクラスは[Enumerableというモジュール](http://docs.ruby-lang.org/ja/2.1.0/class/Enumerable.html)が入っています。all?はEnumerableのメソッドで、
「各要素に対してブロックを評価し、すべての結果 が真である場合に true を返します。ブロックが偽を返した時点で、 ただちに false を返します。」

**Comment by t-tutiya** [comment]
なるる。必要なのはまさにそれ（１個でもfalseならfalseを返す）なので、これでいけそうですね。プルリくれたらマージしますー（暫く忙しいのですぐにはできないかもだけど

**Comment by RPGP1** [comment]
大丈夫でしたか。
分かりました。後でプルリクしますね。

**Comment by RPGP1** [comment]
プルリクしましたので、このIssueをcloseします。
